use clause;
-- JOINS
-- INNER JOINS -- IS USED TO DISPLAY COMMON ROWS IN DIFFERENT TABLES

CREATE TABLE Department 
( 
Department_ID INT PRIMARY KEY, 
Department_Name VARCHAR(30) 
); 
INSERT INTO Department VALUES 
(1,'Sales'), 
(2,'HR'), 
(3,'Finance'), 
(4,'IT'), 
(6,'Marketing');

SELECT * FROM Department;

CREATE TABLE Employe 
( 
Emp_ID INT PRIMARY KEY, 
Emp_Name VARCHAR(30), 
Department_ID INT, 
Salary DECIMAL(10,2) 
); 
INSERT INTO Employe VALUES 
(101,'John',1,45000), 
(102,'Alice',2,55000), 
(103,'David',3,60000), 
(104,'Ravi',4,50000), 
(105,'Meena',2,40000), 
(106,'Karthik',5,65000);

SELECT * FROM Employe;

SELECT E.EMP_ID,E.EMP_NAME, D.Department_id FROM DEPARTMENT D
INNER JOIN EMPLOYE E
ON D.Department_id = E.DEPARTMENT_ID;

-- RIGHT JOIN( DISPLAY ALL ROWS FROM THE RIGHT AND MATCHING ROWS IN LEFT TABLE)

SELECT * 
FROM DEPARTMENT D
RIGHT JOIN EMPLOYE E
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID;

-- LEFT JOIN(SHOWS ALL THE VALUES IN LEFT AND MATCHING FROM RIGHT)

SELECT * 
FROM DEPARTMENT D
LEFT JOIN EMPLOYE E
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID;

-- FULL OUTER JOIN( MATCHING ROWS FROM BOTH THE TABLE AND ALSO UNMATCHING ROWS FROM ALL THE TABLE BUT NOT CONSIDER THE DUPLICATE VALUES)

-- SYNTAX
SELECT COLUMNNAME
FROM TABLENAME_1
LEFT JOIN TABLENAME_2
ON TABLENAME1.COMMOM_COLUMN =TABLENAME2.COMMOM_COLUMN
UNION
SELECT COLUMNNAME
FROM TABLENAME_1
RIGHT JOIN TABLENAME_2
ON TABLENAME1.COMMOM_COLUMN =TABLENAME2.COMMOM_COLUMN;

SELECT * 
FROM DEPARTMENT D
LEFT JOIN EMPLOYE E
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
UNION
SELECT * 
FROM DEPARTMENT D
RIGHT JOIN EMPLOYE E
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID;

-- UNION ALL( MATCHING ROWS FROM BOTH THE TABLE AND ALSO UNMATCHING ROWS FROM ALL THE TABLE AND ALSO CONSIDER THE DUPLICATE VALUES)

SELECT * 
FROM DEPARTMENT D
LEFT JOIN EMPLOYE E
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
UNION ALL
SELECT * 
FROM DEPARTMENT D
RIGHT JOIN EMPLOYE E
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID;

-- CROSS JOIN( RETURNS CARTESIAN PRODUCT- EVERY ROW FROM THE 1ST TABLE COMBINES WITH EVERY ROW FROM 2ND TABLE)
SELECT E.EMP_ID, E.EMP_NAME,E.SALARY,D.DEPARTMENT_ID
FROM DEPARTMENT D
CROSS JOIN EMPLOYE E;

-- SELF JOIN

CREATE TABLE EmployeeS
( 
Emp_ID INT, 
Emp_Name VARCHAR(30), 
Manager_ID INT 
); 
INSERT INTO EmployeeS VALUES 
(101,'John',NULL), 
(102,'Alice',101), 
(103,'David',101), 
(104,'Ravi',102), 
(105,'Meena',103);

SELECT * FROM EmployeeS;